In [3]:
## B. Import Library
import pandas as pd
import nltk
from pathlib import Path
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download("punkt")
nltk.download("punkt_tab")

print("Library siap digunakan.")

Library siap digunakan.

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
## C. Load Dataset
candidate_paths = [
    Path("../dataset/dataset.csv"),
    Path("dataset.csv"),
    Path("../dataset.csv"),
    Path("/mnt/data/dataset.csv")
]

dataset_path = next((p for p in candidate_paths if p.exists()), None)
if dataset_path is None:
    raise FileNotFoundError(
        "Dataset tidak ditemukan. Letakkan dataset.csv di folder dataset "
        "atau sesuaikan candidate_paths."
    )

data = pd.read_csv(dataset_path)
text_column = "comment"

print("Lokasi dataset:", dataset_path)
print("Ukuran dataset:", data.shape)
print("Kolom:", data.columns.tolist())
display(data.head())

Lokasi dataset: dataset.csv
Ukuran dataset: (220051, 8)
Kolom: ['video_id', 'comment_id', 'parent_comment_id', 'level', 'username', 'nickname', 'comment', 'create_time']

,video_id,comment_id,parent_comment_id,level,username,nickname,comment,create_time
0,7.526460e+18,7.643300e+18,NaN,0.0,jbm123jayabetonmandiri,Christian sudartio,Beliau bilang untung nya 2 m ?,5/24/2026 10:58
1,7.526460e+18,7.643360e+18,7.643300e+18,1.0,sahrulmustakimm,sahrul,Makasih Mas,5/24/2026 14:47
2,7.526460e+18,7.643370e+18,7.643300e+18,1.0,jbm123jayabetonmandiri,Christian sudartio,Gimana untung nya 2 m..barang yg di jual ajh g...,5/24/2026 15:13
3,7.526460e+18,7.643370e+18,7.643300e+18,1.0,sahrulmustakimm,sahrul,[Sticker] dibilang Makasih Mas udah 2M itu,5/24/2026 15:35
4,7.526460e+18,7.643370e+18,7.643300e+18,1.0,jbm123jayabetonmandiri,Christian sudartio,😳😳😳,5/24/2026 15:12

In [4]:
## D. Pemeriksaan dan Persiapan Data
print("Jumlah baris awal:", len(data))
print("Missing value pada kolom teks:", data[text_column].isna().sum())
print("Duplikat teks sebelum cleaning:", data[text_column].dropna().duplicated().sum())

data_teks = data.dropna(subset=[text_column]).copy()
data_teks[text_column] = data_teks[text_column].astype(str)
data_teks = data_teks.drop_duplicates(subset=[text_column]).copy()
data_teks = data_teks.reset_index(drop=True)

print("Jumlah komentar setelah menghapus nilai kosong dan duplikat:", len(data_teks))
display(data_teks[[text_column]].head())

Jumlah baris awal: 220051
Missing value pada kolom teks: 304
Duplikat teks sebelum cleaning: 101933
Jumlah komentar setelah menghapus nilai kosong dan duplikat: 117814

                                             comment
0                     Beliau bilang untung nya 2 m ?
1                                        Makasih Mas
2  Gimana untung nya 2 m..barang yg di jual ajh g...
3         [Sticker] dibilang Makasih Mas udah 2M itu
4                                                😳😳😳

In [5]:
## E. Sentence Segmentation
text = (
    "Saya belajar NLP. "
    "NLP sangat menarik. "
    "Saya ingin menjadi NLP Engineer."
)

sentences = sent_tokenize(text)
for i, sentence in enumerate(sentences, start=1):
    print(f"Kalimat {i}: {sentence}")
print("Jumlah kalimat:", len(sentences))

Kalimat 1: Saya belajar NLP.
Kalimat 2: NLP sangat menarik.
Kalimat 3: Saya ingin menjadi NLP Engineer.
Jumlah kalimat: 3

In [6]:
## F. Word Tokenization
text = "Saya belajar Natural Language Processing."
tokens = word_tokenize(text)

print("Teks asli:", text)
print("Hasil tokenisasi:", tokens)
print("Jumlah token:", len(tokens))

Teks asli: Saya belajar Natural Language Processing.
Hasil tokenisasi: ['Saya', 'belajar', 'Natural', 'Language', 'Processing', '.']
Jumlah token: 6

In [7]:
## G. Character Tokenization
text = "NLP"
characters = list(text)

print("Teks asli:", text)
print("Hasil character tokenization:", characters)
print("Jumlah karakter:", len(characters))

Teks asli: NLP
Hasil character tokenization: ['N', 'L', 'P']
Jumlah karakter: 3

In [8]:
## H. Tokenisasi Dataset
data_teks["tokens"] = data_teks[text_column].apply(word_tokenize)
data_teks["jumlah_token"] = data_teks["tokens"].apply(len)

display(data_teks[[text_column, "tokens", "jumlah_token"]].head(10))

,comment,tokens,jumlah_token
0,Beliau bilang untung nya 2 m ?,"[Beliau, bilang, untung, nya, 2, m, ?]",7
1,Makasih Mas,"[Makasih, Mas]",2
2,Gimana untung nya 2 m..barang yg di jual ajh g...,"[Gimana, untung, nya, 2, m, .., barang, yg, di...",16
3,[Sticker] dibilang Makasih Mas udah 2M itu,"[[, Sticker, ], dibilang, Makasih, Mas, udah, ...",9
4,😳😳😳,[😳😳😳],1
5,"Kalo niat membantu UMKM, harusnya koprasi mera...","[Kalo, niat, membantu, UMKM, ,, harusnya, kopr...",122
6,sabar mbak paling 6 bulan dah tutup,"[sabar, mbak, paling, 6, bulan, dah, tutup]",7
7,"kalo ternyata harga murah, saya harap bisa ber...","[kalo, ternyata, harga, murah, ,, saya, harap,...",11
8,"SAYA SETUJU BANG, soalnya saya punya warung 😔","[SAYA, SETUJU, BANG, ,, soalnya, saya, punya, ...",9
9,Ancen Dancuk 🥵🥵🥵,"[Ancen, Dancuk, 🥵🥵🥵]",3

In [10]:
## I. Statistik Jumlah Token
print("Statistik jumlah token per komentar:")
display(data_teks["jumlah_token"].describe())

print("Jumlah dokumen setelah cleaning:", len(data_teks))
print("Total token:", data_teks["jumlah_token"].sum())
print("Rata-rata token per dokumen:", round(data_teks["jumlah_token"].mean(), 2))

Statistik jumlah token per komentar:

count    117814.000000
mean         10.428633
std          11.569733
min           1.000000
25%           4.000000
50%           7.000000
75%          12.000000
max         706.000000
Name: jumlah_token, dtype: float64

Jumlah dokumen setelah cleaning: 117814
Total token: 1228639
Rata-rata token per dokumen: 10.43

In [11]:
## J. Perbandingan Jumlah Kata dan Jumlah Token
data_teks["jumlah_kata"] = data_teks[text_column].apply(lambda x: len(x.split()))

display(data_teks[[text_column, "jumlah_kata", "jumlah_token"]].head(10))
display(data_teks[["jumlah_kata", "jumlah_token"]].describe())

,comment,jumlah_kata,jumlah_token
0,Beliau bilang untung nya 2 m ?,7,7
1,Makasih Mas,2,2
2,Gimana untung nya 2 m..barang yg di jual ajh g...,14,16
3,[Sticker] dibilang Makasih Mas udah 2M itu,7,9
4,😳😳😳,1,1
5,"Kalo niat membantu UMKM, harusnya koprasi mera...",109,122
6,sabar mbak paling 6 bulan dah tutup,7,7
7,"kalo ternyata harga murah, saya harap bisa ber...",9,11
8,"SAYA SETUJU BANG, soalnya saya punya warung 😔",8,9
9,Ancen Dancuk 🥵🥵🥵,3,3

         jumlah_kata   jumlah_token
count  117814.000000  117814.000000
mean        9.428480      10.428633
std        10.339934      11.569733
min         1.000000       1.000000
25%         4.000000       4.000000
50%         7.000000       7.000000
75%        11.000000      12.000000
max       706.000000     706.000000

In [12]:
## K. Eksperimen Tokenisasi
texts = [
    "Saya suka produk ini.",
    "Bagus banget!!!",
    "Tidak bagus...",
    "Harga Rp50.000.",
    "email@example.com",
    "https://example.com",
    "yg bagus bgt sih",
    "aku udah beli nih kak"
]

for sample in texts:
    print("TEXT :", sample)
    print("TOKEN:", word_tokenize(sample))
    print("JUMLAH TOKEN:", len(word_tokenize(sample)))
    print("-" * 50)

TEXT : Saya suka produk ini.
TOKEN: ['Saya', 'suka', 'produk', 'ini', '.']
JUMLAH TOKEN: 5
--------------------------------------------------
TEXT : Bagus banget!!!
TOKEN: ['Bagus', 'banget', '!', '!', '!']
JUMLAH TOKEN: 5
--------------------------------------------------
TEXT : Tidak bagus...
TOKEN: ['Tidak', 'bagus', '...']
JUMLAH TOKEN: 3
--------------------------------------------------
TEXT : Harga Rp50.000.
TOKEN: ['Harga', 'Rp50.000', '.']
JUMLAH TOKEN: 3
--------------------------------------------------
TEXT : email@example.com
TOKEN: ['email', '@', 'example.com']
JUMLAH TOKEN: 3
--------------------------------------------------
TEXT : https://example.com
TOKEN: ['https', ':', '//example.com']
JUMLAH TOKEN: 3
--------------------------------------------------
TEXT : yg bagus bgt sih
TOKEN: ['yg', 'bagus', 'bgt', 'sih']
JUMLAH TOKEN: 4
--------------------------------------------------
TEXT : aku udah beli nih kak
TOKEN: ['aku', 'udah', 'beli', 'nih', 'kak']
JUMLAH TOKEN: 5
--------------------------------------------------

In [13]:
## L. Perbandingan Tokenizer: NLTK dan split()
comparison_texts = [
    "Saya belajar NLP.",
    "Bagus banget!!!",
    "Harga Rp50.000",
    "yg bagus bgt sih",
    "https://example.com"
]

comparison_rows = []
for sample in comparison_texts:
    nltk_tokens = word_tokenize(sample)
    split_tokens = sample.split()
    comparison_rows.append({
        "Teks": sample,
        "NLTK word_tokenize": nltk_tokens,
        "Jumlah token NLTK": len(nltk_tokens),
        "split()": split_tokens,
        "Jumlah hasil split": len(split_tokens)
    })

comparison_df = pd.DataFrame(comparison_rows)
display(comparison_df)

,Teks,NLTK word_tokenize,Jumlah token NLTK,split(),Jumlah hasil split
0,Saya belajar NLP.,"[Saya, belajar, NLP, .]",4,"[Saya, belajar, NLP.]",3
1,Bagus banget!!!,"[Bagus, banget, !, !, !]",5,"[Bagus, banget!!!]",2
2,Harga Rp50.000,"[Harga, Rp50.000]",2,"[Harga, Rp50.000]",2
3,yg bagus bgt sih,"[yg, bagus, bgt, sih]",4,"[yg, bagus, bgt, sih]",4
4,https://example.com,"[https, :, //example.com]",3,[https://example.com],1

In [ ]:
## M. Tokenisasi Karakter pada Dataset
if not data_teks.empty:
    sample_text = data_teks[text_column].iloc[0]
    characters = list(sample_text)
    print("Contoh komentar:", sample_text)
    print("Karakter:", characters)
    print("Jumlah karakter:", len(characters))
else:
    print("Tidak ada komentar yang dapat diproses.")

Contoh komentar: Beliau bilang untung nya 2 m ?
Karakter: ['B', 'e', 'l', 'i', 'a', 'u', ' ', 'b', 'i', 'l', 'a', 'n', 'g', ' ', 'u', 'n', 't', 'u', 'n', 'g', ' ', 'n', 'y', 'a', ' ', '2', ' ', 'm', ' ', '?']
Jumlah karakter: 30